import Head from 'next/head'

export default function Home() {
return (
<div>
   <Head>
    <title>Create Next App</title>
    <meta name='description'
 	content='Generated by create next app' />
    <link rel='icon' href='/favicon.ico' />
   </Head>
 
 <div classname='bg-slate-500 p-2'>
 <h1 className='text-3xl  font-bold'> Next shop</h1>
 <p> hurhyeon </p>
 </div>
  </div>
 )
}