import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
return (
   
   <Layout title='Home'>Homepage
<div> 
   <Head>
   <meta name='description'
   content='Generated by create next app' />
   <link rel='icon' href='/favicon.ico' />
   </Head>

   <div classname='bg-slate-500 p-2'>
   <h1 className='text-3xl  font-bold'> Next shop</h1>
   <p> hurhyeon </p>
   </div>
   </div>
</Layout>
  )
}